version: "3.0"
services:
  etp-threat:
    image: akamai/uls:latest
    restart: always
    env_file: etp-threat.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
      - type: bind
        source: /path/to/your/uls-var-dir/
        target: /opt/akamai-uls/uls/var/
        read_only: false