version: "3.0"
services:
  # THREAT
  etp-threat:
    image: akamai/uls:latest
    restart: always
    env_file: etp-threat.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
  # AUP
  etp-aup:
    image: akamai/uls:latest
    restart: always
    env_file: etp-aup.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
  # DNS
  etp-aup:
    image: akamai/uls:latest
    restart: always
    env_file: etp-dns.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
  # PROXY
  etp-aup:
    image: akamai/uls:latest
    restart: always
    env_file: etp-proxy.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
# EAA
  # ACCESS
  eaa-access:
    image: akamai/uls:latest
    restart: always
    env_file: eaa-access.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
  # ADMIN
  eaa-admin:
    image: akamai/uls:latest
    restart: always
    env_file: eaa-admin.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
# MFA
  # AUTH
  mfa-auth:
    image: akamai/uls:latest
    restart: always
    env_file: mfa-auth.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true
  # POLICY
  mfa-policy:
    image: akamai/uls:latest
    restart: always
    env_file: mfa-policy.env
    volumes:
      - type: bind
        source: /path/to/your/.edgerc
        target: /opt/akamai-uls/.edgerc
        read_only: true